export const specialties = [
  { icon: "🏥", name: "General" },
  { icon: "❤️", name: "Cardiologist" },
  { icon: "🧠", name: "Neurologist" },
  { icon: "👶", name: "Paediatrician" },
];
export const nearbyDoctors = [
  {
    id: 1,
    name: "Dr. Alex Ben",
    specialty: "General Specialist",
    location: "Ontario",
    rating: 4.6,
    experience: "6 Years Experience",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=100&h=100&fit=crop&crop=face",
  },
  {
    id: 2,
    name: "Dr. William Osler",
    specialty: "Cardiologist",
    location: "Toronto",
    rating: 4.9,
    experience: "8 Years Experience",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100&h=100&fit=crop&crop=face",
  },
  {
    id: 3,
    name: "Dr. William Blakes",
    specialty: "Surgeon",
    location: "New York",
    rating: 4.7,
    experience: "4 Years Experience",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100&h=100&fit=crop&crop=face",
  },
  {
    id: 4,
    name: "Dr. Oscar Bradley",
    specialty: "Neurologist",
    location: "Brazil",
    rating: 4.7,
    experience: "6 Years Experience",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100&h=100&fit=crop&crop=face",
  },
];

export const diseases = [
  { name: "Neurofibromatosis" },
  { name: "AIDS/HIV" },
  { name: "Alzheimer’s Disease" },
  { name: "Amyotrophic Lateral Sclerosis (ALS)" },
  { name: "Aneurysm" },
  { name: "Autism Spectrum Disorder (ASD)" },
  { name: "Bipolar Disorder" },
  { name: "Brugada Syndrome" },
  { name: "Cancer" },
  { name: "Celiac Disease" },
  { name: "Cerebral Palsy" },
  { name: "Charcot-Marie-Tooth Disease" },
  { name: "Chronic Fatigue Syndrome (CFS)" },
  { name: "Chronic Infectious Diseases" },
  { name: "Chronic Kidney Disease" },
  { name: "Chronic Liver Disease & Cirrhosis" },
  { name: "Chronic Obstructive Pulmonary Disease (COPD)" },
  { name: "Chronic Pancreatitis" },
  { name: "Congenital Heart Diseases" },
  { name: "Congestive Heart Failure" },
  { name: "Crohn’s Disease" },
  { name: "Cystic Fibrosis" },
  { name: "Dementia" },
  { name: "Diabetes (Type 1 & Type 2)" },
  { name: "Dilated Cardiomyopathy" },
  { name: "Eating Disorders" },
  { name: "Ehlers-Danlos Syndrome" },
  { name: "Endometriosis" },
  { name: "Epilepsy" },
  { name: "Fibromyalgia" },
  { name: "Hemochromatosis" },
  { name: "Hepatitis B & C" },
  { name: "Hereditary Spastic Paraplegia" },
  { name: "Huntington’s Disease" },
  { name: "Leukemia" },
  { name: "Lymphoma" },
  { name: "Lynch Syndrome" },
  { name: "Motor Neurological Diseases" },
  { name: "Multiple Sclerosis" },
  { name: "Muscular Dystrophy" },
  { name: "Myasthenia Gravis" },
  { name: "Neuropathy" },
  { name: "Paraneoplastic Syndrome" },
  { name: "Parkinson’s Disease" },
  { name: "Polycystic Kidney Disease" },
  { name: "Polymyalgia Rheumatica" },
  { name: "Renal Failure" },
  { name: "Rheumatoid Arthritis" },
  { name: "Schizophrenia" },
  { name: "Short Bowel Syndrome" },
  { name: "Sickle Cell Disease" },
  { name: "Spinal Muscular Atrophy (SMA)" },
  { name: "Systemic Lupus Erythematosus (SLE)" },
  { name: "Systemic Sclerosis" },
  { name: "Ulcerative Colitis" },
];
export const specialities = [
  { name: "Electrodessication" },
  { name: "Hematology & Oncology" },
  { name: "Medical Genetics and Genomics" },
  { name: "Multidisciplinary" },
  { name: "Neuro Oncology & Neurology" },
  { name: "Neuro-oncology" },
  { name: "Neurology" },
  { name: "Neurology: Medical Genetics and Genomics" },
  { name: "Neurology: Ophthalmology" },
  { name: "Neurosurgery" },
  { name: "Oncology" },
  { name: "Ophthalmology" },
  { name: "Orthopaedic Surgery" },
  { name: "Otolaryngology" },
  { name: "Otolaryngology: Neurology" },
  { name: "Otolaryngology: Ophthalmology" },
  { name: "Otology: Neurotology" },
  { name: "Pain" },
  { name: "Pathology" },
  { name: "Pediatric Medical Genetics and Genomics" },
  { name: "Pediatric Multidisciplinary" },
  { name: "Pediatric Neurology" },
  { name: "Pediatric Neurosurgery" },
  { name: "Pediatric Oncology" },
  { name: "Pediatric Otolaryngology" },
  { name: "Plastic Surgery" },
  { name: "Radiation Oncology" },
  { name: "Radiology" },
  { name: "Rehabilitation" },
  { name: "Surgical Oncology" },
];

export const states = [
  { name: "Alabama" },
  { name: "Alaska" },
  { name: "Arizona" },
  { name: "Arkansas" },
  { name: "California" },
  { name: "Colorado" },
  { name: "Connecticut" },
  { name: "Delaware" },
  { name: "District of Columbia" },
  { name: "Florida" },
  { name: "Georgia" },
  { name: "Hawaii" },
  { name: "Idaho" },
  { name: "Illinois" },
  { name: "Indiana" },
  { name: "Iowa" },
  { name: "Kansas" },
  { name: "Kentucky" },
  { name: "Louisiana" },
  { name: "Maine" },
  { name: "Maryland" },
  { name: "Massachusetts" },
  { name: "Michigan" },
  { name: "Minnesota" },
  { name: "Mississippi" },
  { name: "Missouri" },
  { name: "Montana" },
  { name: "Nebraska" },
  { name: "Nevada" },
  { name: "New Hampshire" },
  { name: "New Jersey" },
  { name: "New Mexico" },
  { name: "New York" },
  { name: "North Carolina" },
  { name: "North Dakota" },
  { name: "Ohio" },
  { name: "Oklahoma" },
  { name: "Oregon" },
  { name: "Pennsylvania" },
  { name: "Puerto Rico" },
  { name: "Rhode Island" },
  { name: "South Carolina" },
  { name: "South Dakota" },
  { name: "Tennessee" },
  { name: "Texas" },
  { name: "Utah" },
  { name: "Vermont" },
  { name: "Virginia" },
  { name: "Washington" },
  { name: "West Virginia" },
  { name: "Wisconsin" },
  { name: "Wyoming" },
];
